server:
  port: 8080




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost




spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: mscatalogo-service
          uri: lb://mscatalogo-service
          predicates:
            - Path=/categoria/** ,/producto/**

        - id: mscliente-service
          uri: lb://mscliente-service
          predicates:
            - Path=/clientes/**

        - id: mspedido-service
          uri: lb://mspedido-service
          predicates:
            - Path=/pedidos/** ,/pedidodetalle/**


