server:
  port: 8080




eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone :   ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: mscatalogo-service
          uri: lb://mscatalogo-service
          predicates:
            - Path=/categoria/** ,/producto/**
          filters:
            - AuthFilter

        - id: mscliente-service
          uri: lb://mscliente-service
          predicates:
            - Path=/clientes/**

        - id: mspedido-service
          uri: lb://mspedido-service
          predicates:
            - Path=/pedidos/** ,/pedidodetalle/**

        - id: msauth-service
          uri: lb://msauth-service
          predicates:
            - Path=/auth/**



